import { DichVuDaChiDinh } from "../../models/DichVuDaChiDinhModel";
import { DSKQ } from "../../models/DanhSachKetQuaModels";

export const DichVuDaChiDinhData: DichVuDaChiDinh[] = [
  {
    loaiDV: 'Xét nghiệm',
    maDV: '',
    tenDV: 'Xét nghiệm sinh hóa máu',
    tgChiDinh: '15/07/2023 15:45:23',
    trangThai: 'Đã trả kết quả',
  },
  {
    loaiDV: 'CĐHA-TDCN',
    maDV: '',
    tenDV: 'Chụp X-quang xương cẳng chân',
    tgChiDinh: '15/07/2023 15:45:23',
    trangThai: 'Đã trả kết quả',
  },
]

export const DanhSachKetQua: DSKQ[] = [
  {
    idNhom: "wegth",
    tenNhom: "Tổng phân tích tế bào máu ngoại vi (bằng máy đếm laser)",
    dsDichVu: [
      {
        barcode: "",
        maChiSo: "TT37.80.01",
        tenChiSo: "WBC: SL Bạch Cầu",
        ketQua: 5,
        triSoBinhThuong: "4 - 10",
        donViTinh: "G/l",
        soLuong: 1,
        trangThai: "Chờ xử lý",
        maMayXN: "MAY1",
        ghiChu: "",
      },
      {
        barcode: "",
        maChiSo: "TT37.80.02",
        tenChiSo: "RBC: SL Hồng cầu",
        ketQua: 6,
        triSoBinhThuong: "3.9 - 5.8",
        donViTinh: "T/l",
        soLuong: 1,
        trangThai: "Đã xử lý",
        maMayXN: "MAY2",
        ghiChu: "",
      },
      {
        barcode: "",
        maChiSo: "TT37.80.02",
        tenChiSo: "RBC: SL Hồng cầu",
        ketQua: 6,
        triSoBinhThuong: "3.9 - 5.8",
        donViTinh: "T/l",
        soLuong: 1,
        trangThai: "Đã xử lý",
        maMayXN: "MAY2",
        ghiChu: "",
      },
      {
        barcode: "",
        maChiSo: "TT37.80.02",
        tenChiSo: "RBC: SL Hồng cầu",
        ketQua: 6,
        triSoBinhThuong: "3.9 - 5.8",
        donViTinh: "T/l",
        soLuong: 1,
        trangThai: "Đã xử lý",
        maMayXN: "MAY2",
        ghiChu: "",
      },
      {
        barcode: "",
        maChiSo: "TT37.80.02",
        tenChiSo: "RBC: SL Hồng cầu",
        ketQua: 6,
        triSoBinhThuong: "3.9 - 5.8",
        donViTinh: "T/l",
        soLuong: 1,
        trangThai: "Đã xử lý",
        maMayXN: "MAY2",
        ghiChu: "",
      },
    ],
  },
  {
    idNhom: "kaej",
    tenNhom: "Tổng phân tích tế bào máu ngoại vi (bằng máy đếm tổng trở)",
    dsDichVu: [
      {
        barcode: "",
        maChiSo: "TT37.80.01",
        tenChiSo: "WBC: SL Bạch Cầu",
        ketQua: 5,
        triSoBinhThuong: "4 - 10",
        donViTinh: "G/l",
        soLuong: 1,
        trangThai: "Chờ xử lý",
        maMayXN: "MAY1",
        ghiChu: "",
      },
      {
        barcode: "",
        maChiSo: "TT37.80.02",
        tenChiSo: "RBC: SL Hồng cầu",
        ketQua: 6,
        triSoBinhThuong: "3.9 - 5.8",
        donViTinh: "T/l",
        soLuong: 1,
        trangThai: "Đã xử lý",
        maMayXN: "MAY2",
        ghiChu: "",
      },
    ],
  },
  {
    idNhom: "srtjtydj",
    tenNhom: "Tổng phân tích nước tiểu (bằng máy tự động)",
    dsDichVu: [
      {
        barcode: "",
        maChiSo: "TT37.80.01",
        tenChiSo: "WBC: SL Bạch Cầu",
        ketQua: 5,
        triSoBinhThuong: "4 - 10",
        donViTinh: "G/l",
        soLuong: 1,
        trangThai: "Chờ xử lý",
        maMayXN: "MAY1",
        ghiChu: "",
      },
      {
        barcode: "",
        maChiSo: "TT37.80.02",
        tenChiSo: "RBC: SL Hồng cầu",
        ketQua: 6,
        triSoBinhThuong: "3.9 - 5.8",
        donViTinh: "T/l",
        soLuong: 1,
        trangThai: "Đã xử lý",
        maMayXN: "MAY2",
        ghiChu: "",
      },
    ],
  },
];