
const initialMapJsonToAttributes: any = {
  manufacturingCountry: null,
  unitOfMeasurement: null,
  manufacturer: null,
  solvent: null,
  activeGradient: null,
  associateActiveGradient: null,
  routeOfUse: null,
  characteristics: null,
  abcVenGroup: null,
  pharmacologicalGroup: null,
  drugClass: null,
  drugType: null,
  insuredPerson: null,
  medicalInsuranceCostGroups: null,
  accountCode: null,
  volume: null,
  intensity: null,
  importer: null,
  usageInstructions: null,
  healthInsuranceCode: null,
  healthInsuranceMedicineName: null,
  concentration: null,
  specialtyDrug: null,
  storageCondition: null,
  nationalDrugCode: null,
};

export const initFormThuoc: any = {
  name: "",
  id: "",
  unit: null,
  type: null,
  attribute: null,
  groups: null,
  note: "",
  targetUnits: null,
  registrationNumber: "",
  inNetworkCoveragePercentage: "",
  outOfNetworkCoveragePercentage: "",
  unitId: null,
  code: "",
  images: null,
  attributeValues: initialMapJsonToAttributes,
};
