import { ContractInfo, OptionsInfo,ContractAnnexInfo, AllowanceInfo} from "../models/ContractModels";

export const contracts: ContractInfo[] = [
  {
    signingDate: "2022-05-20",
    number: "003",
    workerFullName: "Alex Johnson",
    jobPosition: "Sales Representative",
    signingUnit: "DEF Corporation",
    type: "Full-time",
    duration: "2 years",
    effectiveDate: "2022-06-01",
    expirationDate: "2024-06-01",
    baseSalary: "4000",
    insuranceContribution: "400",
    signingStatus: "Signed",
    status: "Active",
  },
  {
    signingDate: "2022-08-10",
    number: "004",
    workerFullName: "Emily Wilson",
    jobPosition: "Accountant",
    signingUnit: "GHI Corporation",
    type: "Full-time",
    duration: "1 year",
    effectiveDate: "2022-09-01",
    expirationDate: "2023-09-01",
    baseSalary: "4500",
    insuranceContribution: "450",
    signingStatus: "Signed",
    status: "Active",
  },
  {
    signingDate: "2022-11-25",
    number: "005",
    workerFullName: "Michael Brown",
    jobPosition: "Software Developer",
    signingUnit: "JKL Company",
    type: "Full-time",
    duration: "3 years",
    effectiveDate: "2023-01-01",
    expirationDate: "2026-01-01",
    baseSalary: "6000",
    insuranceContribution: "600",
    signingStatus: "Signed",
    status: "Active",
  },
  {
    signingDate: "2022-12-15",
    number: "006",
    workerFullName: "Sarah Davis",
    jobPosition: "Marketing Specialist",
    signingUnit: "MNO Corporation",
    type: "Part-time",
    duration: "6 months",
    effectiveDate: "2023-01-01",
    expirationDate: "2023-07-01",
    baseSalary: "2500",
    insuranceContribution: "250",
    signingStatus: "Signed",
    status: "Active",
  },
  {
    signingDate: "2023-03-05",
    number: "007",
    workerFullName: "Robert Wilson",
    jobPosition: "Human Resources Manager",
    signingUnit: "PQR Company",
    type: "Full-time",
    duration: "2 years",
    effectiveDate: "2023-04-01",
    expirationDate: "2025-04-01",
    baseSalary: "5500",
    insuranceContribution: "550",
    signingStatus: "Signed",
    status: "Active",
  },
  {
    signingDate: "2023-06-10",
    number: "008",
    workerFullName: "Sophia Martinez",
    jobPosition: "Graphic Designer",
    signingUnit: "STU Corporation",
    type: "Full-time",
    duration: "1 year",
    effectiveDate: "2023-07-01",
    expirationDate: "2024-07-01",
    baseSalary: "3500",
    insuranceContribution: "350",
    signingStatus: "Signed",
    status: "Active",
  },
  {
    signingDate: "2023-09-20",
    number: "009",
    workerFullName: "William Thompson",
    jobPosition: "Project Manager",
    signingUnit: "VWX Company",
    type: "Full-time",
    duration: "2 years",
    effectiveDate: "2023-10-01",
    expirationDate: "2025-10-01",
    baseSalary: "5800",
    insuranceContribution: "580",
    signingStatus: "Signed",
    status: "Active",
  },
  {
    signingDate: "2023-12-01",
    number: "010",
    workerFullName: "Olivia Anderson",
    jobPosition: "Customer Service Representative",
    signingUnit: "YZ Corporation",
    type: "Part-time",
    duration: "6 months",
    effectiveDate: "2024-01-01",
    expirationDate: "2024-07-01",
    baseSalary: "2000",
    insuranceContribution: "200",
    signingStatus: "Signed",
    status: "Active",
  },
  {
    signingDate: "2022-01-01",
    number: "001",
    workerFullName: "John Doe",
    jobPosition: "Manager",
    signingUnit: "ABC Company",
    type: "Full-time",
    duration: "1 year",
    effectiveDate: "2022-02-01",
    expirationDate: "2023-02-01",
    baseSalary: "5000",
    insuranceContribution: "500",
    signingStatus: "Signed",
    status: "Active",
  },
  {
    signingDate: "2022-03-15",
    number: "002",
    workerFullName: "Jane Smith",
    jobPosition: "Engineer",
    signingUnit: "XYZ Corporation",
    type: "Part-time",
    duration: "6 months",
    effectiveDate: "2022-04-01",
    expirationDate: "2022-10-01",
    baseSalary: "3000",
    insuranceContribution: "300",
    signingStatus: "Signed",
    status: "Active",
  },
];
export const CONTRACT_DUARATIONS: OptionsInfo[] = [
  {
    name: "1 tháng",
    id: "1",
  },
  {
    name: "2 tháng",
    id: "2",
  },
  {
    name: "6 tháng",
    id: "3",
  },
  {
    name: "1 năm",
    id: "4",
  },
  {
    name: "3 năm",
    id: "5",
  },
];
export const contractAnnex: ContractAnnexInfo[] = [
  {
    number: "001",
    name: "Contract 1",
    effectiveDateAnnex: "2023-06-01",
    signingUnit: "Company A",
    jobPosition: "Engineer",
    typeContract: "Full-time",
    effectiveDateContract: "2023-07-01",
    expirationDate: "2024-06-30",
    baseSalary: "$5000",
    insuranceContribution: "$500",
    salaryRate: "Monthly",
    attachments: "Annex A",
  },
  {
    number: "002",
    name: "Contract 2",
    effectiveDateAnnex: "2023-06-05",
    signingUnit: "Company B",
    jobPosition: "Manager",
    typeContract: "Part-time",
    effectiveDateContract: "2023-08-01",
    expirationDate: "2023-12-31",
    baseSalary: "$3000",
    insuranceContribution: "$300",
    salaryRate: "Hourly",
    attachments: "Annex B",
  },
  {
    number: "003",
    name: "Contract 3",
    effectiveDateAnnex: "2023-06-10",
    signingUnit: "Company C",
    jobPosition: "Analyst",
    typeContract: "Full-time",
    effectiveDateContract: "2023-09-01",
    expirationDate: "2024-08-31",
    baseSalary: "$4000",
    insuranceContribution: "$400",
    salaryRate: "Monthly",
    attachments: "Annex C",
  },
];
export const allowances: AllowanceInfo[] = [
  {
    name: "Transportation Allowance",
    value: "$200",
    payroll: "Monthly",
    note: "Provided for commuting expenses.",
  },
  {
    name: "Housing Allowance",
    value: "$500",
    payroll: "Monthly",
    note: "Provided for housing expenses.",
  },
  {
    name: "Meal Allowance",
    value: "$100",
    payroll: "Daily",
    note: "Provided for daily meals.",
  },
];