export interface IVatTuTrongKho {
  maThuoc?: string;
  tenThuoc?: string;
  hoatChat?: string;
  hamLuong?: string;
  donVi?: string;
  soLo?: string;
  soHopDong?: string;
  ngayHopDong?: string;
  tonKho?: string;
  choXuat?: string;
  dongBang?: string;
  hanDung?: string;
  soDangKy?: string;
  dauKy?: string;
  giaMua?: string;
  giaBan?: string;
  giaDichVu?: string;
  giaBaoHiem?: string;
  giaVienPhi?: string;
  ngayNhap?: string;
  phongLuu?: string;
  quyetDinhTrungThau?: string;
  soGoiThau?: string;
  nhomThau?: string;
  namThau?: string;
  medicineStore?: string;
  medicineId?: string;
}